const resList = [
    {
      id: "242282",
      name: "McDonald's",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/9/8874a698-b2fe-4838-a02f-d4288ba3cdf0_242282.JPG",
      locality: "Rajiv Chowk",
      areaName: "Connaught Place",
      costForTwo: "₹400 for two",
      cuisines: ["American", "Burgers", "Fast Food"],
      avgRating: 4.5,
      parentId: "630",
      avgRatingString: "4.5",
      totalRatingsString: "2.9K+",
      deliveryTime: 26,
      lastMileTravel: 2.7,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "2.7 km",
    },
    {
      id: "8614",
      name: "Burger King",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/24/2d2383cf-fab7-4413-917e-ad2a1c41e250_8614.jpg",
      locality: "Connaught Place",
      areaName: "Connaught Place",
      costForTwo: "₹350 for two",
      cuisines: ["American", "Burgers", "Fast Food"],
      avgRating: 4.4,
      parentId: "630",
      avgRatingString: "4.4",
      totalRatingsString: "2.9K+",
      deliveryTime: 26,
      lastMileTravel: 2.7,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "2.7 km",
    },
    {
      id: "10477",
      name: "Chaayos Chai+Snacks=Relax",
      cloudinaryImageId: "2beebd3688e63e027ee8a11c1c8a72c8",
      locality: "Connaught Place",
      areaName: "Connaught Place",
      costForTwo: "₹250 for two",
      cuisines: ["Bakery", "Beverages", "Street Food", "Italian", "Desserts"],
      avgRating: 4.6,
      parentId: "630",
      avgRatingString: "4.6",
      totalRatingsString: "2.9K+",
      deliveryTime: 26,
      lastMileTravel: 2.7,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "2.7 km",
    },
];

export default resList;